# Generated by Django 5.2.7 on 2025-11-16 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookshelf', '0003_alter_book_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'permissions': (('can_view', 'Can view books'), ('can_create', 'Can add a new book'), ('can_delete', 'Can delete books'), ('can_edit', 'Can edit books'))},
        ),
    ]
