# Generated by Django 5.2.7 on 2025-11-14 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('relationship_app', '0002_userprofile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'permissions': (('can_add_book', 'Can add a new book'), ('can_delete_book', 'Can delete a book'), ('can_change_book', 'Can edit a book'))},
        ),
    ]
